// src/components/Layouts/Container.tsx
import Head from "next/head"
import { useRouter } from "next/router"
import styles from "./Container.module.scss"

interface ContainerProps {
  children: React.ReactNode
  title?: string
  description?: string
  image?: string
}

export default function Container(props: ContainerProps) {
  const router = useRouter()

  const SITE_TITLE = "MyFursona"
  const MAIN_DESCRIPTION =
    "A place where users can manage their fursonas! The project is currently under construction."

  const url = `https://myfursona.art${router.asPath}`
  const dynamicTitle =
    router.pathname === "/"
      ? SITE_TITLE
      : `${props.title ? props.title : router.pathname} - ${SITE_TITLE}`

  const dynamicDesc =
    router.pathname !== "/" ? MAIN_DESCRIPTION : props.description

  return (
    <>
      <Head>
        <title>{dynamicTitle}</title>
        <meta
          name="description"
          content={props.description && MAIN_DESCRIPTION}
        />
        <meta
          name="keywords"
          content="furry, fursona, furry fandom, MyFursona, ref sheet"
        />
        <meta property="og:title" content={dynamicTitle} />
        <meta property="og:description" content={dynamicDesc} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={url} />
        <meta name="twitter:title" content={dynamicTitle} />
        <meta name="twitter:description" content={dynamicDesc} />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:url" content={url} />
        <link rel="canonical" href={url} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles["content-wrap"]}>{props.children}</main>
    </>
  )
}

// components/Container.vue
<script lang="ts" setup>
const route = useRoute();
const urlPath = `https://www.myfursona.art${route.fullPath}`;

const props = defineProps<{
  title: string;
  description: string;
  class?: string;
  nowrap?: boolean;
}>();

const detectWrap = !props.nowrap ? "wrap-contents" : "";
const detectClass = !props.class ? detectWrap : `${detectWrap} ${props.class}`;

useHead({
  title: props.title,
  meta: [
    { name: "description", content: props.description },
    { property: "og:title", content: props.title },
    { property: "og:description", content: props.description },
    { property: "og:type", content: "website" },
    { property: "og:url", content: urlPath },
    { name: "twitter:title", content: props.title },
    { name: "twitter:description", content: props.description },
    { name: "twitter:card", content: "summary_large_image" },
    { name: "twitter:url", content: urlPath },
  ],
  link: [{ rel: "canonical", href: urlPath }],
});
</script>

<template>
  <main id="page-container" :class="detectClass">
    <slot />
  </main>
</template>

<style>
.wrap-contents {
  @apply mx-auto max-w-screen-2xl px-6;
}
</style>
