// website/components/Dropdown/DropdownItem.vue
<script setup lang="ts">
import { ChevronDownIcon } from "lucide-vue-next"

defineProps<{
	text: string
	icon?: Component
	contents?: boolean
}>()

const slots = useSlots()
</script>

<template>
	<div
		biro-ui-menu-item
		:data-accordion="!slots.default ? undefined : ''"
		:aria-label="text"
	>
		<component
			:is="!slots.default ? 'a' : 'button'"
			role="menuitem"
			class="block w-full px-4 py-3 font-medium cursor-pointer select-none hover:bg-base-500"
			tabindex="0"
		>
			<div class="flex justify-between">
				<div class="flex items-center gap-x-2.5">
					<component :is="icon" aria-hidden="true" />
					<span>{{ text }}</span>
				</div>
				<ChevronDownIcon id="chevron" />
			</div>
		</component>
		<div id="slot" class="empty:hidden">
			<slot />
		</div>
	</div>
</template>

<style lang="scss">
[biro-ui-menu-item] {
	display: block;

	&:not([data-accordion]) {
		display: contents;
	}

	&:not([data-accordion]) #chevron {
		display: none !important;
	}

	&[data-accordion] #chevron {
		display: block;
	}
}
</style>

// apps/website/src/components/ui/Dropdown/DropdownItem.tsx
import Link from "next/link"
import { Menu } from "@headlessui/react"
import type { ReactMapElement } from "@/types"
import clsx from "clsx"

export default function DropdownItem({
  children,
  link,
  prefix,
  suffix,
  disabled,
  ...attributes
}: {
  children?: React.ReactNode
  link?: string
  disabled?: boolean
  prefix?: React.ReactElement
  suffix?: React.ReactElement
} & Pick<ReactMapElement<"button">, "onClick" | "onKeyDown" | "aria-label">) {
  return (
    <Menu.Item>
      {({ active }) => (
        <Link
          href={link as any}
          className={clsx(
            "w-full rounded-md transition-colors",
            active && "bg-400 text-700"
          )}
        >
          <span className="flex w-max select-none items-center justify-between gap-x-2 px-3 py-2 font-medium">
            {prefix}
            {children}
            {suffix}
          </span>
        </Link>
      )}
    </Menu.Item>
  )
}
